Fix Typescript errors
Fixes Typescript errors in MedicationsPage.tsx and MedicationManager.tsx.
- Fixes error TS2339: Property 'Icon' does not exist on type 'ForwardRefExoticComponent<ButtonProps & RefAttributes<HTMLButtonElement>>'.
- Fixes error TS2322: Type '{ refreshKey: number; }' is not assignable to type 'IntrinsicAttributes & { refreshTrigger?: number; }'. Property 'refreshKey' does not exist on type 'IntrinsicAttributes & { refreshTrigger?: number; }'.